
Skip to content

    rakeshdhundhara
    /
    git-test

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

Workflow Dispatch Input AWS region (Create_main and destroy)
Workflow Dispatch Input AWS region (Create_main and destroy) #2

Jobs

Run details

Workflow file for this run
.github/workflows/tf_main.yml at 87af519
name: Workflow Dispatch Input AWS region (Create_main and destroy)

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-south-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{ github.event.inputs.region }}
          
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init
      working-directory: module/
      
    - name: Plan Terraform
      run: terraform plan -var-file=rakesh.tfvars -out=tfplan
      working-directory: module/

    - name: Apply Terraform
      run: terraform apply -var-file=rakesh.tfvars -auto-approve "tfplan"
      working-directory: module/
      
   
